version: '3.6'

services:
  kma_php:
    container_name: kma_php
    build:
      context: ./docker
      dockerfile: php-fpm.dockerfile
    volumes:
      - .:/var/www
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    tty: true
    networks:
      - docker-network

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - docker-network

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: "no"
    environment:
      MARIADB_ROOT_PASSWORD: 'password'
      MARIADB_DATABASE: 'kma'
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: 'password'
    ports:
      - 3306:3306
    networks:
      - docker-network

  clickhouse:
    container_name: clickhouse
    image: bitnami/clickhouse
    ports:
      - 8123:8123
      - 9000:9000
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_ADMIN_USER=user
      - CLICKHOUSE_ADMIN_PASSWORD=password
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge
